const SECTIONS: { title: string; body: (string | string[])[] }[] = [
  {
    title: 'Getting started',
    body: [
      'Type an IUPAC name or a SMILES string in the box on the Name tab and select Build. The application draws the 2D structure, builds a 3D model that respects the stereochemistry in your name, and lists the properties of the molecule.',
      'The Examples list on the left contains molecules that show common features. Select any entry to load it.',
      'As you type, a tick or a cross appears in the box. A cross means the name cannot be read yet; the reason is shown under the box. A dropdown offers names that match what you have typed so far.',
    ],
  },
  {
    title: 'Stereochemistry',
    body: [
      'Stereochemistry comes only from the name. Descriptors such as (2R), (3S), (E), (Z), cis and trans are read and applied. Centres that the name leaves undefined are marked with a question mark, and the application never guesses them.',
      'The Stereochemistry panel lists every stereocentre and stereogenic double bond with its label. Select a label to see why it is R or S (or E or Z): the panel shows the CIP priorities of the substituents, the rule applied, and a drawing with the priorities marked.',
      'Mirror image builds the enantiomer and shows both molecules side by side. Flip this centre inverts a single centre so you can compare diastereomers. Open this one loads the second molecule in the main view.',
      'If a descriptor in the name does not fit (for example a stereo label on a carbon that is not a stereocentre), the structure is still built and a warning explains what was ignored.',
    ],
  },
  {
    title: 'The 2D and 3D views',
    body: [
      'The 2D view shows wedge and hash bonds for stereocentres and labels each centre. The 3D view can be rotated by dragging, zoomed with the scroll wheel and panned with shift and drag. Use the style menu to switch between ball and stick, stick, space filling and wireframe. Labels toggles the R, S, E and Z markers on the model; Spin rotates the model continuously; Reset restores the default view.',
      'Measure lets you read geometry from the model. Select two atoms for a distance, three for an angle, or four for a dihedral. The value appears on the model and under the viewer.',
      'The 3D geometry is generated by a conformer search and force field optimisation, then checked so that the stereochemistry it shows matches the name.',
    ],
  },
  {
    title: 'Functional groups and properties',
    body: [
      'The Functional groups panel lists every group detected in the molecule. Select a group to highlight its atoms in both views.',
      'The Properties panel reports formula, molecular weight, exact mass, logP, topological polar surface area, hydrogen bond donors and acceptors, rotatable bonds, ring counts, stereocentre count, formal charge and QED, together with a Lipinski rule of five summary.',
    ],
  },
  {
    title: 'Projections',
    body: [
      'For molecules with a suitable single bond, the Projections panel draws a Newman projection along that bond. Choose the bond from the list and use the slider to rotate the rear carbon; the dihedral angle and whether the conformation is staggered or eclipsed are shown.',
      'For saturated six membered rings, the Chair view draws the chair conformation taken from the 3D model, marks each substituent as axial or equatorial, and offers a ring flip to display the alternative chair.',
    ],
  },
  {
    title: 'Drawing structures',
    body: [
      'The Draw tab opens a structure editor. Draw a molecule with the atom and bond tools, use the wedge and hash bond tools to set stereocentres, and select Build 3D. The result appears below the editor and is shown with its SMILES, since drawn structures do not carry a name.',
      'Copy to editor, available on every result, loads the current molecule into the editor so you can modify it and build again.',
    ],
  },
  {
    title: 'Batch processing',
    body: [
      'The Batch tab accepts up to 200 names or SMILES strings, one per line. Run produces a table with formula, molecular weight, InChIKey, stereo summary and SMILES for each entry. Lines that cannot be read show the reason and, where possible, a suggested correction that can replace the line with one click.',
      'Open shows any row in the full viewer below the table. Download CSV saves the table for use in a spreadsheet.',
    ],
  },
  {
    title: 'Quiz',
    body: [
      'The Quiz tab shows a structure and asks for its name. Three levels are available: small molecules, molecules with functional groups, and molecules with stereochemistry.',
      'Your answer is checked by structure, not by spelling, so any correct name is accepted. If the skeleton is right but the stereochemistry differs, the feedback says so. Show answer reveals the accepted names, which can be opened in the viewer. Signed in users have their attempts recorded.',
    ],
  },
  {
    title: 'Mistyped names',
    body: [
      'When a name cannot be read, the application explains the problem in plain language, underlines the part it could not understand, and offers up to three corrections under Did you mean. Corrections are never applied automatically; select one to use it.',
      'Copy and paste artefacts such as curly quotes, long dashes and trailing punctuation are cleaned up before the name is read.',
    ],
  },
  {
    title: 'Accounts and saving',
    body: [
      'Create an account with Log in / Register to save molecules. Save stores the current molecule with a label and an optional collection. Saved molecules appear in the left column grouped by collection; select the pencil icon to add notes or move an entry to another collection.',
      'Share copies a link to the current molecule. Anyone with the link sees the same structure.',
    ],
  },
  {
    title: 'Downloads',
    body: [
      'Every result can be downloaded as an SVG or PNG drawing, a MOL file containing the 3D coordinates, or a SMILES file.',
    ],
  },
  {
    title: 'Appearance',
    body: [
      'Use the sun and moon control in the header to switch between light and dark mode. The choice is remembered on this device. Structure drawings keep a white background in both modes for legibility.',
    ],
  },
]

export function GuidePanel() {
  return (
    <div className="guide">
      <section className="card guide-card">
        <header className="card-head"><h2>User guide</h2></header>
        <nav className="guide-nav" aria-label="Guide sections">
          {SECTIONS.map((s) => (
            <a key={s.title} href={`#guide-${s.title.toLowerCase().replace(/[^a-z]+/g, '-')}`}>{s.title}</a>
          ))}
        </nav>
        {SECTIONS.map((s) => (
          <section key={s.title} id={`guide-${s.title.toLowerCase().replace(/[^a-z]+/g, '-')}`} className="guide-section">
            <h3>{s.title}</h3>
            {s.body.map((p, i) =>
              Array.isArray(p) ? (
                <ul key={i}>{p.map((li) => <li key={li}>{li}</li>)}</ul>
              ) : (
                <p key={i}>{p}</p>
              ),
            )}
          </section>
        ))}
      </section>
    </div>
  )
}
