const SECTIONS: { title: string; body: (string | string[])[] }[] = [
  {
    title: 'Getting started',
    body: [
      'Type an IUPAC name or a SMILES string in the box on the Name tab and select Build. The application draws the 2D structure, builds a 3D model that respects the stereochemistry in your name, and lists the properties of the molecule.',
      'The Examples list on the left contains molecules that show common features. Select any entry to load it.',
      'As you type, a tick or a cross appears in the box. A cross means the name cannot be read yet; the reason is shown under the box. A dropdown offers names that match what you have typed so far. A SMILES with a structural error (an atom with too many bonds, a ring that cannot be aromatic) is reported per atom, for example C2 has 5 bonds.',
      'Build from a peptide or nucleotide sequence, under the box, turns a sequence into the structure: a peptide as one-letter (AGSK) or three-letter (Ala-Gly-Ser) codes, written N to C terminus, in the L or D series; DNA or RNA written 5\u2032 to 3\u2032; or HELM notation. Molecules up to about 18 amino acids or 7 nucleotides are accepted.',
    ],
  },
  {
    title: 'Stereochemistry',
    body: [
      'Stereochemistry comes only from the name. Descriptors such as (2R), (3S), (E), (Z), cis and trans are read and applied. Centres that the name leaves undefined are marked with a question mark, and the application never guesses them.',
      'The Stereochemistry panel lists every stereocentre and stereogenic double bond with its label. Select a label to see why it is R or S (or E or Z): the panel shows the CIP priorities of the substituents, the rule applied, and a drawing with the priorities marked.',
      'Mirror image builds the enantiomer and shows both molecules side by side. Flip this centre inverts a single centre so you can compare diastereomers. Open this one loads the second molecule in the main view.',
      'If a descriptor in the name does not fit (for example a stereo label on a carbon that is not a stereocentre), the structure is still built and a warning explains what was ignored.',
    ],
  },
  {
    title: 'The 2D and 3D views',
    body: [
      'The 2D view shows wedge and hash bonds for stereocentres and labels each centre. The 3D view can be rotated by dragging, zoomed with the scroll wheel and panned with shift and drag. Use the style menu to switch between ball and stick, stick, space filling and wireframe. Labels toggles the R, S, E and Z markers on the model; Spin rotates the model continuously; Reset restores the default view.',
      'Measure lets you read geometry from the model. Select two atoms for a distance, three for an angle, or four for a dihedral. The value appears on the model and under the viewer.',
      'The 3D geometry is generated by a conformer search and force field optimisation, then checked so that the stereochemistry it shows matches the name.',
    ],
  },
  {
    title: 'Functional groups and properties',
    body: [
      'The Functional groups panel lists every group detected in the molecule. Select a group to highlight its atoms in both views.',
      'The Properties panel reports formula, molecular weight, exact mass, logP, topological polar surface area, hydrogen bond donors and acceptors, rotatable bonds, ring counts, stereocentre count, formal charge and QED, together with a Lipinski rule of five summary.',
      'Show elemental analysis adds a table with the number of atoms, the mass and the mass percentage of each element, in Hill order.',
    ],
  },
  {
    title: 'Name lookup, resonance and orbitals',
    body: [
      'Structures that were drawn or entered as SMILES have no name. Look up name asks PubChem for the IUPAC name and common name when the compound is known there; Use as input loads the name. This needs an internet connection.',
      'The Resonance forms panel appears when a molecule has more than one Kekule or charge separated form. Every form is drawn on the same layout so only the bonds and charges move.',
      'Hovering an atom in the 3D view shows its hybridisation, lone pairs and charge. The Orbitals toggle labels every heavy atom. The Surface toggle draws the molecular surface coloured by partial charge, red for negative and blue for positive.',
      'Compare with... overlays a second molecule on the current one, aligned on their common substructure, and reports the RMSD. Enantiomers and conformers show a clear difference; identical molecules superimpose.',
    ],
  },
  {
    title: 'Structure and bonding',
    body: [
      'The Structure and bonding panel groups several short analyses of the current molecule. Hover a row or a chip to highlight the atoms it refers to.',
      'Chirality states whether the molecule is chiral, achiral or meso, with the reason. A meso compound shows the pair of equivalent centres that carry opposite descriptors. The verdict is only given when every stereocentre is specified in the name.',
      'Shapes lists the VSEPR geometry of every atom with two or more neighbours: electron domains, lone pairs, the shape name, the ideal angle and the angle measured in the 3D model.',
      'Aromaticity examines every ring: the pi electron count with a per atom breakdown, whether the ring is fully conjugated, and the Huckel verdict.',
      'Unsaturation gives the degrees of unsaturation from the formula and from the structure (rings, double bonds and triple bonds) side by side.',
      'Oxidation states shows the oxidation number of each heavy atom on the drawing. Select an atom chip to see how the number was obtained.',
      'Polarity classifies every bond as nonpolar, polar or ionic from the electronegativity difference and marks the negative end. The dipole moment is estimated from partial charges on the 3D model; Show arrow in 3D draws it on the model, pointing to the negative end.',
      'H-bonding colours hydrogen bond donors and acceptors on the drawing and gives an estimate of water solubility with the reasons behind it.',
    ],
  },
  {
    title: 'Acids, bases and isotopes',
    body: [
      'The Acids and bases panel appears when the molecule has an ionisable group. Each site is listed with its group, a typical pKa and the fraction ionised at the chosen pH. Move the pH slider or select a preset (stomach, blood, intestine, or the isoelectric point when the molecule has both an acid and a base) and the drawing updates to the dominant form at that pH, with the net charge.',
      'The pKa values are textbook values for each type of group, not predictions for the specific molecule, so treat them as accurate to about one unit.',
      'Isotope labels lets you replace an atom, or some of the hydrogens on an atom, with a heavier isotope such as deuterium, carbon-13, nitrogen-15 or oxygen-18. The panel shows the labelled structure, the isotopic formula, the exact mass and the mass shift.',
    ],
  },
  {
    title: 'Fischer and Haworth projections',
    body: [
      'For open chain molecules with stereocentres on a carbon chain, such as sugars and amino acids, the Fischer tab draws the Fischer projection: the chain runs vertically with the most oxidised carbon on top, vertical bonds point away from you and horizontal bonds towards you. Left and right are read from the 3D model. The D or L series is stated when the molecule is a sugar or an amino acid.',
      'For cyclic sugars (a five or six membered ring with one oxygen and an anomeric carbon) the Haworth tab draws the ring with the thick edge nearest to you and every substituent up or down. The panel names the anomer (alpha or beta), the D or L series and the reasoning.',
    ],
  },
  {
    title: 'Conformational energy',
    body: [
      'Bond rotation scans the energy of the molecule as a chosen single bond is turned through 360 degrees in 10 degree steps, relaxing everything else at each step with the MMFF94 force field. The plot shows the staggered minima and eclipsed maxima and the barrier between them. Select a point on the plot to see that conformer as a Newman projection.',
      'Chair flip compares the two chair forms of a substituted six membered ring. Both chairs are drawn with their axial and equatorial groups, the energy difference is given, and the panel states which chair dominates and roughly what fraction of the mixture it makes up at room temperature.',
      'The Conformers and energy panel searches more widely. Find conformers embeds several starting geometries, minimises each with MMFF94 and lists the distinct results with their energy above the lowest, the fraction of the mixture each would make up at room temperature, and the heavy atom RMSD from the lowest one. Select a row to see that conformer in a small 3D view. Minimise model reports the steric energy of the geometry shown in the main 3D view before and after minimisation.',
      'These are force field energies. They reproduce trends well (a tert-butyl group locks the ring, an anti conformation beats a gauche one) but are not measured values.',
    ],
  },
  {
    title: 'Spectra',
    body: [
      'The Spectra panel predicts the 1H and 13C NMR, IR and mass spectra of the current molecule. Hover a peak or a table row to highlight the atoms responsible.',
      '1H NMR: hydrogens are grouped into signals by symmetry, with a chemical shift, an integration and a multiplicity. The multiplicity comes from first-order coupling: each signal lists its coupling constants (for example dd, J = 8.0, 2.0 Hz). Typical values are used: 7 Hz across a freely rotating single bond, the Karplus value for the dihedral in the lowest energy conformer inside rings, 16 Hz trans and 10.5 Hz cis across a double bond, 8 Hz ortho and 2 Hz meta on a benzene ring, and 2.5 Hz between an aldehyde hydrogen and its neighbour. Hydrogens on oxygen and nitrogen exchange and appear as broad singlets. The drawing builds each multiplet from its real coupling constants, with the splitting exaggerated so it can be seen. Shifts come from nmrshiftdb2 when the service is reachable and from additive rules otherwise; expect about 0.5 ppm (1H) and 10 ppm (13C) of error.',
      '13C NMR: one signal per set of equivalent carbons with its environment. IR: the characteristic bands of every functional group present, drawn as a synthetic transmittance curve and listed with their range and intensity. When the NIST WebBook holds an experimental IR or mass spectrum for the compound it is overlaid and linked.',
      'Mass spectrum: the molecular ion with its isotope pattern, and a fragmentation tree. Ions in the first row come straight from the molecular ion: the most stable single bond cleavages (acylium, benzylic and allylic, alpha to a heteroatom), the McLafferty rearrangement of carbonyl compounds with a gamma hydrogen, and characteristic neutral losses such as water from alcohols, CO from aldehydes and phenols, HCN from nitriles, CO2 from acids and HX from alkyl halides. Under those sit second step ions: an acylium loses CO, the tropylium ion at m/z 91 loses ethyne to m/z 65, and alkyl cations lose ethene down the 29, 43, 57 series. Each ion is drawn with its charge; ions containing chlorine or bromine show their M+2 partner. Peak heights in the drawing rank the ions by expected stability and are not intensities.',
    ],
  },
  {
    title: 'Name breakdown',
    body: [
      'For molecules built from a name, the Name breakdown panel colours each part of the name: stereo descriptors, locants, multipliers, substituents, ring prefix, parent chain, saturation and suffix. Hover a part to highlight its atoms in both views. Parts the breakdown does not recognise are shown in grey; the name itself was still read correctly.',
    ],
  },
  {
    title: 'Projections',
    body: [
      'For molecules with a suitable single bond, the Projections panel draws a Newman projection along that bond. Choose the bond from the list and use the slider to rotate the rear carbon; the dihedral angle and whether the conformation is staggered or eclipsed are shown.',
      'For saturated six membered rings, the Chair view draws the chair conformation taken from the 3D model, marks each substituent as axial or equatorial, and offers a ring flip to display the alternative chair.',
    ],
  },
  {
    title: 'Drawing structures',
    body: [
      'The Draw tab opens a structure editor. Draw a molecule with the atom and bond tools, use the wedge and hash bond tools to set stereocentres, and select Build 3D. The result appears below the editor and is shown with its SMILES, since drawn structures do not carry a name.',
      'Copy to editor, available on every result, loads the current molecule into the editor so you can modify it and build again. On the Draw tab the side lists are hidden so the editor and its result use the full width.',
      'Insert template adds a ready made structure to the canvas next to whatever is already there: the twenty amino acids, nucleobases and nucleosides, sugars in open chain and ring forms, steroids and terpenes, heterocycles, carbocycles, and common reagents and solvents. The structure arrives with its natural stereochemistry.',
      'The editor also has a structure library of its own (the book icon), and an enhanced stereochemistry tool. Marking centres as racemic (AND) or relative (OR) is understood: the model can only show one configuration, so the result carries a warning saying which centres were drawn as a mixture or with unknown absolute configuration. If a drawn structure has a valence problem, the message names the atom.',
    ],
  },
  {
    title: 'Isomers',
    body: [
      'The Isomers tab lists the constitutional isomers of a molecular formula, for example C4H10O or C5H10. It handles formulas with up to eight heavy atoms, the elements C, H, N, O and halogens, at most two heteroatoms, and at most one ring or one double bond. Acyclic and cyclic isomers are grouped, each isomer lists its stereoisomers, and the total including stereoisomers is shown. Enol and gem-diol tautomers are omitted. Select any structure to open it in the viewer.',
    ],
  },
  {
    title: 'Reactions',
    body: [
      'A reaction SMILES such as CC(=O)O.CCO>>CC(=O)OCC.O, entered in the Name tab, draws the reaction with reactants, agents and products, lists each component with its formula, and reports whether the atoms balance. Components open in the viewer. Atom map numbers in the SMILES ([CH3:1][OH:2]) colour the matching atoms on both sides of the arrow, so you can follow where each atom goes.',
      'Show stoichiometry opens a grid for the reaction. Enter a coefficient for each component (the SMILES carries none) and the mass of at least one reactant; the grid fills in millimoles, equivalents, the limiting reagent, and the theoretical yield of each product. Enter the mass actually obtained to get the percentage yield.',
      'Under every molecule, the Reactions panel lists the textbook reactions it can undergo (What can it make) with the reagents, the product and the rule that decides the regiochemistry: Markovnikov or anti-Markovnikov additions, Zaitsev or Hofmann eliminations, ortho, para or meta substitution on an aromatic ring. Where can it come from lists one step disconnections: the precursors and the reaction that would make the molecule. Select any product or precursor to load it and continue forwards or backwards.',
      'When you enter a reaction (reactants>>products) the Reaction panel names the reaction when it matches one of the templates, states the reaction type, and for substitutions and eliminations says whether SN1, SN2, E1 or E2 is expected from the substitution pattern of the reacting carbon.',
    ],
  },
  {
    title: 'Mechanisms',
    body: [
      'The Mechanisms tab holds a library of twenty curved arrow mechanisms grouped by type: substitution (SN1, SN2, Williamson), elimination (E1, E2), additions to alkenes, carbonyl chemistry (esterification, ester hydrolysis, cyanohydrin, Grignard, borohydride reduction, imine formation, aldol, amide formation), electrophilic aromatic substitution, the Diels-Alder reaction and radical chlorination.',
      'Select a mechanism and step through it with Previous and Next or the numbered dots. Each step shows the species involved, the curved arrows for that step and a caption explaining what moves and why. A full arrow moves an electron pair; a fishhook arrow (radical mechanisms) moves a single electron. The last step shows the products and offers to open the main product on the Name tab.',
    ],
  },
  {
    title: 'Batch processing',
    body: [
      'The Batch tab accepts up to 200 names or SMILES strings, one per line. Run produces a table with formula, molecular weight, InChIKey, stereo summary and SMILES for each entry. Lines that cannot be read show the reason and, where possible, a suggested correction that can replace the line with one click.',
      'Open shows any row in the full viewer below the table. Download CSV saves the table for use in a spreadsheet.',
    ],
  },
  {
    title: 'Quiz',
    body: [
      'The Quiz tab shows a structure and asks for its name. Three levels are available: small molecules, molecules with functional groups, and molecules with stereochemistry.',
      'Your answer is checked by structure, not by spelling, so any correct name is accepted. If the skeleton is right but the stereochemistry differs, the feedback says so. Show answer reveals the accepted names, which can be opened in the viewer. Signed in users have their attempts recorded.',
      'Level 4, Draw it, shows a name and an editor: draw the structure and select Check. Timed mode allows 60 seconds per question and reveals the answer when time runs out. Signed in users see My progress with accuracy, current streak and recent attempts.',
    ],
  },
  {
    title: 'Worksheets',
    body: [
      'Worksheet, available on each saved collection, produces a printable PDF with eight structures per page. Choose structures only, with blank lines for names and an answer key on the last page, or structures with names.',
    ],
  },
  {
    title: 'Mistyped names',
    body: [
      'When a name cannot be read, the application explains the problem in plain language, underlines the part it could not understand, and offers up to three corrections under Did you mean. Corrections are never applied automatically; select one to use it.',
      'Copy and paste artefacts such as curly quotes, long dashes and trailing punctuation are cleaned up before the name is read.',
    ],
  },
  {
    title: 'Accounts and saving',
    body: [
      'Create an account with Log in / Register to save molecules. Save stores the current molecule with a label and an optional collection. Saved molecules appear in the left column grouped by collection; select the pencil icon to add notes or move an entry to another collection.',
      'The search box above the saved list finds molecules by structure. Type a SMILES or SMARTS: entries that contain it as a substructure are shown; if nothing contains it, the list is ranked by similarity instead, with the percentage beside each entry.',
      'Share copies a link to the current molecule. Anyone with the link sees the same structure.',
      'The Recent list under Examples keeps the last twenty molecules built in this browser.',
    ],
  },
  {
    title: 'Downloads',
    body: [
      'Every result can be downloaded as an SVG or PNG drawing, a MOL file containing the 3D coordinates, or a SMILES file.',
    ],
  },
  {
    title: 'Site statistics',
    body: [
      'Accounts listed in the ADMIN_USERS setting see a Stats tab with totals, molecules and quiz attempts per day, the most viewed molecules, and the inputs that failed most often. No individual browsing data is recorded; failed inputs are counted without any user information.',
    ],
  },
  {
    title: 'Appearance',
    body: [
      'The application opens in light mode. Use the sun and moon control in the header to switch to dark mode; the choice is remembered on this device. Structure drawings keep a white background in both modes for legibility.',
    ],
  },
]

export function GuidePanel() {
  return (
    <div className="guide">
      <section className="card guide-card">
        <header className="card-head"><h2>User guide</h2></header>
        <nav className="guide-nav" aria-label="Guide sections">
          {SECTIONS.map((s) => (
            <a key={s.title} href={`#guide-${s.title.toLowerCase().replace(/[^a-z]+/g, '-')}`}>{s.title}</a>
          ))}
        </nav>
        {SECTIONS.map((s) => (
          <section key={s.title} id={`guide-${s.title.toLowerCase().replace(/[^a-z]+/g, '-')}`} className="guide-section">
            <h3>{s.title}</h3>
            {s.body.map((p, i) =>
              Array.isArray(p) ? (
                <ul key={i}>{p.map((li) => <li key={li}>{li}</li>)}</ul>
              ) : (
                <p key={i}>{p}</p>
              ),
            )}
          </section>
        ))}
      </section>
    </div>
  )
}
