/** Structure templates for the editor, grouped. SMILES keep stereo so the
 *  fragment arrives with the natural configuration. */
export interface Template {
  name: string
  smiles: string
}

export const TEMPLATE_GROUPS: { group: string; items: Template[] }[] = [
  {
    group: 'Amino acids (L)',
    items: [
      { name: 'Glycine', smiles: 'NCC(=O)O' },
      { name: 'Alanine', smiles: 'C[C@H](N)C(=O)O' },
      { name: 'Valine', smiles: 'CC(C)[C@H](N)C(=O)O' },
      { name: 'Leucine', smiles: 'CC(C)C[C@H](N)C(=O)O' },
      { name: 'Isoleucine', smiles: 'CC[C@H](C)[C@H](N)C(=O)O' },
      { name: 'Proline', smiles: 'OC(=O)[C@@H]1CCCN1' },
      { name: 'Phenylalanine', smiles: 'N[C@@H](Cc1ccccc1)C(=O)O' },
      { name: 'Tyrosine', smiles: 'N[C@@H](Cc1ccc(O)cc1)C(=O)O' },
      { name: 'Tryptophan', smiles: 'N[C@@H](Cc1c[nH]c2ccccc12)C(=O)O' },
      { name: 'Serine', smiles: 'N[C@@H](CO)C(=O)O' },
      { name: 'Threonine', smiles: 'C[C@@H](O)[C@H](N)C(=O)O' },
      { name: 'Cysteine', smiles: 'N[C@@H](CS)C(=O)O' },
      { name: 'Methionine', smiles: 'CSCC[C@H](N)C(=O)O' },
      { name: 'Asparagine', smiles: 'NC(=O)C[C@H](N)C(=O)O' },
      { name: 'Glutamine', smiles: 'NC(=O)CC[C@H](N)C(=O)O' },
      { name: 'Aspartic acid', smiles: 'N[C@@H](CC(=O)O)C(=O)O' },
      { name: 'Glutamic acid', smiles: 'N[C@@H](CCC(=O)O)C(=O)O' },
      { name: 'Lysine', smiles: 'NCCCC[C@H](N)C(=O)O' },
      { name: 'Arginine', smiles: 'N=C(N)NCCC[C@H](N)C(=O)O' },
      { name: 'Histidine', smiles: 'N[C@@H](Cc1c[nH]cn1)C(=O)O' },
    ],
  },
  {
    group: 'Nucleobases and nucleosides',
    items: [
      { name: 'Adenine', smiles: 'Nc1ncnc2[nH]cnc12' },
      { name: 'Guanine', smiles: 'Nc1nc2[nH]cnc2c(=O)[nH]1' },
      { name: 'Cytosine', smiles: 'Nc1cc[nH]c(=O)n1' },
      { name: 'Thymine', smiles: 'Cc1c[nH]c(=O)[nH]c1=O' },
      { name: 'Uracil', smiles: 'O=c1cc[nH]c(=O)[nH]1' },
      { name: 'Adenosine', smiles: 'Nc1ncnc2n(cnc12)[C@@H]1O[C@H](CO)[C@@H](O)[C@H]1O' },
      { name: 'Deoxythymidine', smiles: 'Cc1cn([C@H]2C[C@H](O)[C@@H](CO)O2)c(=O)[nH]c1=O' },
      { name: 'ATP', smiles: 'Nc1ncnc2n(cnc12)[C@@H]1O[C@H](COP(=O)(O)OP(=O)(O)OP(=O)(O)O)[C@@H](O)[C@H]1O' },
    ],
  },
  {
    group: 'Sugars',
    items: [
      { name: 'D-Glucose (open chain)', smiles: 'OC[C@@H](O)[C@@H](O)[C@H](O)[C@@H](O)C=O' },
      { name: 'β-D-Glucopyranose', smiles: 'OC[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O' },
      { name: 'α-D-Glucopyranose', smiles: 'OC[C@H]1O[C@H](O)[C@H](O)[C@@H](O)[C@@H]1O' },
      { name: 'D-Fructose (open chain)', smiles: 'OC[C@@H](O)[C@@H](O)[C@H](O)C(=O)CO' },
      { name: 'β-D-Fructofuranose', smiles: 'OC[C@H]1O[C@](O)(CO)[C@@H](O)[C@@H]1O' },
      { name: 'D-Galactose (open chain)', smiles: 'OC[C@H](O)[C@@H](O)[C@H](O)[C@@H](O)C=O' },
      { name: 'D-Ribose (open chain)', smiles: 'OC[C@@H](O)[C@@H](O)[C@@H](O)C=O' },
      { name: 'β-D-Ribofuranose', smiles: 'OC[C@H]1O[C@@H](O)[C@H](O)[C@@H]1O' },
      { name: '2-Deoxy-D-ribose', smiles: 'OC[C@@H](O)[C@@H](O)CC=O' },
      { name: 'Sucrose', smiles: 'OC[C@H]1O[C@@](CO)(O[C@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)[C@@H](O)[C@@H]1O' },
      { name: 'Lactose', smiles: 'OC[C@H]1O[C@@H](O[C@H]2[C@H](O)[C@@H](O)[C@@H](O)O[C@@H]2CO)[C@H](O)[C@@H](O)[C@H]1O' },
    ],
  },
  {
    group: 'Steroids and terpenes',
    items: [
      { name: 'Gonane (steroid skeleton)', smiles: 'C1CCC2C(C1)CCC1C2CCC2CCCC12' },
      { name: 'Cholesterol', smiles: 'C[C@H](CCCC(C)C)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]1[C@H]2CC=C2C[C@@H](O)CC[C@]12C)C' },
      { name: 'Testosterone', smiles: 'C[C@]12CC[C@H]3[C@@H](CCC4=CC(=O)CC[C@@]34C)[C@@H]1CC[C@@H]2O' },
      { name: 'Estradiol', smiles: 'C[C@]12CC[C@H]3[C@@H](CCc4cc(O)ccc34)[C@@H]1CC[C@@H]2O' },
      { name: 'Progesterone', smiles: 'CC(=O)[C@H]1CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@]4(C)[C@H]3CC[C@]12C' },
      { name: 'Cortisol', smiles: 'C[C@]12CCC(=O)C=C1CC[C@@H]1[C@@H]2[C@@H](O)C[C@@]2(C)[C@H]1CC[C@]2(O)C(=O)CO' },
      { name: 'Cholic acid', smiles: 'C[C@H](CCC(=O)O)[C@H]1CC[C@H]2[C@@H]3[C@H](O)C[C@@H]4C[C@H](O)CC[C@]4(C)[C@H]3C[C@H](O)[C@]12C' },
      { name: 'Isoprene', smiles: 'C=CC(C)=C' },
      { name: 'Limonene', smiles: 'CC1=CC[C@@H](CC1)C(C)=C' },
      { name: 'Menthol', smiles: 'CC(C)[C@@H]1CC[C@@H](C)C[C@H]1O' },
      { name: 'Camphor', smiles: 'CC1(C)[C@@H]2CC[C@@]1(C)C(=O)C2' },
    ],
  },
  {
    group: 'Heterocycles',
    items: [
      { name: 'Pyridine', smiles: 'c1ccncc1' },
      { name: 'Pyrimidine', smiles: 'c1cncnc1' },
      { name: 'Pyrazine', smiles: 'c1cnccn1' },
      { name: 'Pyrrole', smiles: 'c1cc[nH]c1' },
      { name: 'Furan', smiles: 'c1ccoc1' },
      { name: 'Thiophene', smiles: 'c1ccsc1' },
      { name: 'Imidazole', smiles: 'c1c[nH]cn1' },
      { name: 'Pyrazole', smiles: 'c1cn[nH]c1' },
      { name: 'Oxazole', smiles: 'c1cocn1' },
      { name: 'Thiazole', smiles: 'c1cscn1' },
      { name: 'Indole', smiles: 'c1ccc2[nH]ccc2c1' },
      { name: 'Quinoline', smiles: 'c1ccc2ncccc2c1' },
      { name: 'Isoquinoline', smiles: 'c1ccc2cnccc2c1' },
      { name: 'Purine', smiles: 'c1ncc2[nH]cnc2n1' },
      { name: 'Piperidine', smiles: 'C1CCNCC1' },
      { name: 'Piperazine', smiles: 'C1CNCCN1' },
      { name: 'Morpholine', smiles: 'C1COCCN1' },
      { name: 'Tetrahydrofuran', smiles: 'C1CCOC1' },
      { name: 'Pyrrolidine', smiles: 'C1CCNC1' },
      { name: 'Oxirane', smiles: 'C1CO1' },
      { name: 'β-Lactam', smiles: 'O=C1CCN1' },
    ],
  },
  {
    group: 'Carbocycles and aromatics',
    items: [
      { name: 'Benzene', smiles: 'c1ccccc1' },
      { name: 'Naphthalene', smiles: 'c1ccc2ccccc2c1' },
      { name: 'Anthracene', smiles: 'c1ccc2cc3ccccc3cc2c1' },
      { name: 'Phenanthrene', smiles: 'c1ccc2c(c1)ccc1ccccc12' },
      { name: 'Cyclopropane', smiles: 'C1CC1' },
      { name: 'Cyclobutane', smiles: 'C1CCC1' },
      { name: 'Cyclopentane', smiles: 'C1CCCC1' },
      { name: 'Cyclohexane', smiles: 'C1CCCCC1' },
      { name: 'Cyclohexene', smiles: 'C1CCC=CC1' },
      { name: 'Norbornane', smiles: 'C1CC2CCC1C2' },
      { name: 'Adamantane', smiles: 'C1C2CC3CC1CC(C2)C3' },
      { name: 'Cubane', smiles: 'C12C3C4C1C1C2C3C41' },
      { name: 'Decalin', smiles: 'C1CCC2CCCCC2C1' },
    ],
  },
  {
    group: 'Common reagents and solvents',
    items: [
      { name: 'Acetic acid', smiles: 'CC(=O)O' },
      { name: 'Acetone', smiles: 'CC(C)=O' },
      { name: 'Ethyl acetate', smiles: 'CCOC(C)=O' },
      { name: 'DMSO', smiles: 'CS(C)=O' },
      { name: 'DMF', smiles: 'CN(C)C=O' },
      { name: 'Diethyl ether', smiles: 'CCOCC' },
      { name: 'Dichloromethane', smiles: 'ClCCl' },
      { name: 'Toluene', smiles: 'Cc1ccccc1' },
      { name: 'Triethylamine', smiles: 'CCN(CC)CC' },
      { name: 'Pyridinium chlorochromate', smiles: '[O-][Cr](=O)(=O)Cl.c1cc[nH+]cc1' },
      { name: 'Boc anhydride', smiles: 'CC(C)(C)OC(=O)OC(=O)OC(C)(C)C' },
      { name: 'Tosyl chloride', smiles: 'Cc1ccc(cc1)S(=O)(=O)Cl' },
      { name: 'Benzoyl peroxide', smiles: 'O=C(OOC(=O)c1ccccc1)c1ccccc1' },
      { name: 'Aspirin', smiles: 'CC(=O)Oc1ccccc1C(=O)O' },
      { name: 'Caffeine', smiles: 'Cn1cnc2c1c(=O)n(C)c(=O)n2C' },
      { name: 'Ibuprofen', smiles: 'CC(C)Cc1ccc(cc1)[C@H](C)C(=O)O' },
    ],
  },
]
